### ISSUE TITLE
Spack has released a new version - what do we need to update?

### ISSUE THREAD

**Issue by heatherkellyucl** [UCL-ARC/hpc-spack#2]
Given an existing older install with some packages, what do we need to do when Spack itself updates to keep it up to date?

(Ideally in a CI/CD pipeline eventually).

**Comment by heatherkellyucl** [comment]
Updating spacksites to use a new version requires editing spacksites/settings/spack_sites.ini

Will also need to check whether the major changes/deprecations for the new version require any other alterations (if default functionality changes, if methods we are using are deprecated).

**Comment by heatherkellyucl** [comment]
For the upgrade to 0.20.0, need to add the `enable` section to `initial_site_modules.yaml` to make sure TCL modules are enabled.
```
modules:
  default:
    enable:
      - tcl
```

**Comment by heatherkellyucl** [comment]
Since there wasn't anything much in my existing site, am deleting and recreating it:
```
# updated spack version, recreate site
rm -r /shared/ucl/apps/spack-test/hk-initial-stack/
source spacksites/myriad-utilities/init-spacksites-on-myriad.sh
spacksites/spacksites create hk-initial-stack
spacksites/spacksites install-env hk-initial-stack compilers first_compiler.yaml

# get ready to run spack commands as normal for this site
eval $(spacksites/spacksites spack-setup-env hk-initial-stack)
```

While installing compiler, got
```
# SPACKSITES: Have set spacks's external compiler and python dependencies - now calling spack -e compilers install
==> Error: concretization failed for the following reasons:

   1. Cannot satisfy 'readline@8.1.2'. You could consider setting `concretizer:unify` to `when_possible` or `false` to allow multiple versions of some packages.
# SPACKSITES: Now calling: #######
 source /lustre/scratch/scratch/ccspapp/hpc-spack/spacksites/process-env-scripts/spack-deps-rhel-7.8.sh

source  /lustre/shared/ucl/apps/spack-test/hk-initial-stack/spack/share/spack/setup-env.sh
spack config --scope=site get packages
# SPACKSITES: ####################
# SPACKSITES: found first compiler spec in packages.yaml gcc@12.2.0
# SPACKSITES: Now calling: #######
 source /lustre/scratch/scratch/ccspapp/hpc-spack/spacksites/process-env-scripts/spack-deps-rhel-7.8.sh

source  /lustre/shared/ucl/apps/spack-test/hk-initial-stack/spack/share/spack/setup-env.sh
spack -e compilers config get
# SPACKSITES: ####################
# SPACKSITES: Now calling: #######
 source /lustre/scratch/scratch/ccspapp/hpc-spack/spacksites/process-env-scripts/spack-deps-rhel-7.8.sh

source  /lustre/shared/ucl/apps/spack-test/hk-initial-stack/spack/share/spack/setup-env.sh
spack load gcc@12.2.0
spack compiler find --scope=site
# SPACKSITES: ####################
```

**Comment by heatherkellyucl** [comment]
Versions of readline in `spack info --all readline` are
```
Preferred version:  
    8.2    https://ftpmirror.gnu.org/readline/readline-8.2.tar.gz

Safe versions:  
    8.2    https://ftpmirror.gnu.org/readline/readline-8.2.tar.gz
    8.1    https://ftpmirror.gnu.org/readline/readline-8.1.tar.gz
    8.0    https://ftpmirror.gnu.org/readline/readline-8.0.tar.gz
    7.0    https://ftpmirror.gnu.org/readline/readline-7.0.tar.gz
    6.3    https://ftpmirror.gnu.org/readline/readline-6.3.tar.gz
```

**Comment by heatherkellyucl** [comment]
`dev1/first_compiler.yaml` and `dev1/modules/basic_deps_modules.yaml` specify `readline@8.1.2` - that's what is in the buildcache.

**Comment by cjlegg** [comment]
There are two questions:

1. To what extent does what gets built depend on the spack version? I expect old packages built with a prior spack version will be used if they have the same spack spec. However, it may not be certain that two versions of spack This might be a question for the spack Slack. There is the business of the long path name padding, which is under development. To be on the safe side and for clear reproducibilty I would rebuild all packages, including the compilers

**Comment by heatherkellyucl** [comment]
The packages available and unavailable depend on the version of Spack - so some packages we might have in a yaml file could no longer exist (the issue here).

I checked on 2. for this change, and we do not appear to be using any of the deprecated commands at present. We should get some warning with deprecation output when running spacksites before things entirely vanish. I did update initial_modules.yaml based on the release notes (https://github.com/UCL-ARC/hpc-spack/issues/2#issuecomment-1604424326).

(And like Mosè says, the format of spec files is changing in 0.21, so if we'd written any, we'd need to rewrite them).

**Comment by heatherkellyucl** [comment]
- [x] We need a new root at the `/shared/ucl/apps/spack` level (and probably labelled by spack version).
- [x]  Need to change this location in the myriad pull script.
- [x]  Need to create a buildcache in the new place, and build first_compilers in it and push to cache.

Existing sites should remain fine since the spack they have never gets re-pulled, but to continue to develop one of those, they'd need their own checkout of spacksites at a relevant point (use of different branches in one repo in one account is going to confuse us, so suggest a new checkout location - so I should re-check out into `~/Scratch/spack/$version` really).

**Comment by heatherkellyucl** [comment]
We might want to reconfigure this entirely and have `/shared/ucl/apps/spack/$version` as the root level (and only end up keeping two once we get going).

**Comment by heatherkellyucl** [comment]
I have made `/shared/ucl/apps/spack/0.20` for this version's root.
I have created a branch in this repo for 0.20 versions.
I have cloned this into `/home/ccspapp/Scratch/spack/0.20` and `git checkout 0.20`.

Updated locations in git-pull-on-myriad.sh and init-spacksites-on-myriad.sh

- [ ] Make it so those scripts take a version on the command line, eg `git-pull-on-myriad.sh 0.20`

**Comment by heatherkellyucl** [comment]
### Buildcache creation
Current non-deprecated options are:

`spack buildcache push --allow-root /shared/ucl/apps/spack-test/buildcache gcc@12.2.0`

which will take my local install of gcc@12.2.0 and all its dependencies, and put it into a buildcache at that location.

```
[ccspapp@login13 hpc-spack]$ spack buildcache push --allow-root /shared/ucl/apps/spack-test/buildcache gcc@12.2.0
==> Selected 30 specs to push to file:///shared/ucl/apps/spack-test/buildcache
gpg: checking the trustdb
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
==> [ 1/30] Pushed gcc@12.2.0/pzbagbo
==> [ 2/30] Pushed binutils@2.40/kfn3yxv
==> [ 6/30] Pushed texinfo@6.5/vk4bses
...
```

**Comment by heatherkellyucl** [comment]
It is possible that this option to `spack buildcache push` would let us reuse our .yaml files rather than saying gcc@12.2.0.

```
  --spec-file SPEC_FILE
                        Create buildcache entry for spec from json or yaml file
```
