### ISSUE TITLE
Difficulty building first compiler on Myriad

### ISSUE THREAD

**Issue by krishnakumarg1984** [UCL-ARC/hpc-spack#46]
I am following the first compiler recipes on Myriad, and it is extremely slow going and I had to cancel out a few times at the `perl()` build step. 

```
==> Installing perl-5.36.0-tgvequcrg5memfzhqvvjm5jpyzgn3gtk
==> No binary for perl-5.36.0-tgvequcrg5memfzhqvvjm5jpyzgn3gtk found: installing from source
==> Using cached archive: /lustre/home/uccagop/apps/spack/0.20/kg_site/spack/var/spack/cache/_source-cache/archive/e2/e26085af8ac396f62add8a533c3a0ea8c8497d836f0689347ac5abd7b7a4e00a.tar.gz
==> Using cached archive: /lustre/home/uccagop/apps/spack/0.20/kg_site/spack/var/spack/cache/_source-cache/archive/9d/9da50e155df72bce55cb69f51f1dbb4b62d23740fb99f6178bb27f22ebdf8a46.tar.gz
==> Moving resource stage
        source: /lustre/home/uccagop/apps/spack/0.20/kg_site/build_stage/resource-cpanm-tgvequcrg5memfzhqvvjm5jpyzgn3gtk/spack-src/
        destination: /lustre/home/uccagop/apps/spack/0.20/kg_site/build_stage/spack-stage-perl-5.36.0-tgvequcrg5memfzhqvvjm5jpyzgn3gtk/spack-src/cpanm/cpanm
==> Ran patch() for perl
==> perl: Executing phase: 'configure'
```

Was wondering if others have seen a similar issue? I am going to try on Kathleen.

**Comment by heatherkellyucl** [comment]
`perl-5.36.0` is in the buildcache so it should be finding that one.

(There isn't a ccspapp buildcache on Kathleen or Michael yet, only on Young, so I'll get those set up today. You probably want to hold off installing first_compilers.yaml until those are there).

**Comment by heatherkellyucl** [comment]
And if something is taking a long time to build (and it isn't on Myriad while we're having filesystem issues), don't cancel it, just leave it going - and always have it in a tmux or screen session so you can detach.

**Comment by heatherkellyucl** [comment]
It is taking quite some time to fetch gcc from https://mirror.spack.io on Kathleen and Michael today - but appears to be getting there in the end.

**Comment by krishnakumarg1984** [comment]
It is slow. I left it on tmux for now.

**Comment by heatherkellyucl** [comment]
Buildcache exists on Kathleen and Michael now, so installing first_compilers.yaml can be done now and should use those, assuming your buildcache is set to the correct location.
